
[mapper]
double = "f32"
string = "String"
int32 = "i32"
int53 = "i64"
int64 = "i64"
bytes = "String"
boolFalse = "bool"
boolTrue = "bool"
Bool = "bool"
vector = "Vec"
Vector = "Vec"


[filter]

[filter.ProfilePhoto.has_animation]
optional = true
reason = "May be not sent"

[filter.Chat.positions]
optional = true
reason = "May be not sent"

[filter.UpdateChatLastMessage.positions]
optional = true
reason = "May be not sent"



[filter.PageBlockCover]
[filter.PageBlockCover.cover]
sign_type = "Box<PageBlock>"
optional = false
reason = "recursive type"

[filter.TargetChatInternalLink]
[filter.TargetChatInternalLink.link]
sign_type = "Box<InternalLinkType>"
optional = false
reason = "recursive type"


[filter.RichTextPlain]
[filter.RichTextPlain.text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.RichTextBold]
[filter.RichTextBold.text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.RichTextItalic]
[filter.RichTextItalic.text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.RichTextUnderline]
[filter.RichTextUnderline.text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.RichTextStrikethrough]
[filter.RichTextStrikethrough.text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.RichTextFixed]
[filter.RichTextFixed.text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.RichTextUrl]
[filter.RichTextUrl.text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.RichTextEmailAddress]
[filter.RichTextEmailAddress.text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.RichTextSubscript]
[filter.RichTextSubscript.text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.RichTextSuperscript]
[filter.RichTextSuperscript.text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.RichTextMarked]
[filter.RichTextMarked.text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.RichTextPhoneNumber]
[filter.RichTextPhoneNumber.text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.RichTextAnchor]
[filter.RichTextAnchor.text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.RichTexts]
[filter.RichTexts.text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.RichTextReference]
[filter.RichTextReference.text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.RichTextReference.reference_text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.RichTextAnchorLink]
[filter.RichTextAnchorLink.text]
sign_type = "Box<RichText>"
optional = false
reason = "recursive type"

[filter.Messages]
[filter.Messages.messages]
sign_type = "Vec<Option<Message>>"
optional = false
reason = "fix the issue: https://github.com/fewensa/telegram-client/issues/17"


[filter.ChatPhotoInfo]
[filter.ChatPhotoInfo.has_animation]
optional = true

[listener]
#ok = "Ok"
#error = "Error"
#proxy = "Proxy"


